version: '3'

services:
  percona-playback:
    platform: linux/amd64
    container_name: percona-playback
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./slowquery:/volume_dir
